#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

for file in docker-compose*.test.yml; do

    echo "Starting Test in ${file}..."

    ls -al '/srv/dokos/dodock' '/srv/dokos/dodock/sites' '/srv/dokos/dodock/logs'

    # Test container run
    docker-compose --no-ansi -f "${file}" up -d && sleep 60
    docker-compose --no-ansi -f "${file}" logs -f "sut"
    docker-compose --no-ansi -f "${file}" ps
    docker-compose --no-ansi -f "${file}" logs "dodock_db"
    docker-compose --no-ansi -f "${file}" ps "dodock_db" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs "dodock_app"
    docker-compose --no-ansi -f "${file}" ps "dodock_app" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs "dodock_web"
    docker-compose --no-ansi -f "${file}" ps "dodock_web" | grep "Up"
    docker-compose --no-ansi -f "${file}" ps "sut" | grep "Exit 0" || exit 1
    docker-compose --no-ansi -f "${file}" down
    # Test container restart
    docker-compose --no-ansi -f "${file}" up -d && sleep 60
    docker-compose --no-ansi -f "${file}" logs -f "sut"
    docker-compose --no-ansi -f "${file}" ps
    docker-compose --no-ansi -f "${file}" logs "dodock_db"
    docker-compose --no-ansi -f "${file}" ps "dodock_db" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs "dodock_app"
    docker-compose --no-ansi -f "${file}" ps "dodock_app" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs "dodock_web"
    docker-compose --no-ansi -f "${file}" ps "dodock_web" | grep "Up"
    docker-compose --no-ansi -f "${file}" ps "sut" | grep "Exit 0" || exit 1
    docker-compose --no-ansi -f "${file}" down

done
